; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "אוצריא"
#define MyAppVersion "0.9.80"
#define MyAppPublisher "sivan22"
#define MyAppURL "https://github.com/Y-PLONI/otzaria"
#define MyAppExeName "otzaria.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{EEC4F712-CD05-4D15-A753-509E840A51A5}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
PrivilegesRequiredOverridesAllowed=dialog
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputDir=.
OutputBaseFilename=otzaria-{#MyAppVersion}-windows-full
SetupIconFile=white_sketch128x128.ico
Compression=lzma
SolidCompression=yes
; Disable compression for DLL files to prevent corruption
CompressionThreads=1
WizardStyle=modern
DisableDirPage=no

[InstallDelete]
; מחיקת ספריית נתונים ישנה לפני פריסת מסד הנתונים החדש
Type: filesandordirs; Name: "{code:GetDataDir}\books"

[Dirs]
Name: "{commonappdata}\{#MyAppName}"; Permissions: users-modify; Check: IsAdminInstallMode
Name: "{commonappdata}\{#MyAppName}\books"; Permissions: users-modify; Check: IsAdminInstallMode
Name: "{commonappdata}\{#MyAppName}\index"; Permissions: users-modify; Check: IsAdminInstallMode

[Languages]
Name: "hebrew"; MessagesFile: "compiler:Languages\Hebrew.isl"

[Code]

function GetDataDir(Param: String): String;
begin
  if IsAdminInstallMode then
    Result := ExpandConstant('{commonappdata}\{#MyAppName}')
  else
    Result := ExpandConstant('{localappdata}\{#MyAppName}\Data');
end;

function InitializeSetup(): Boolean;
var
  DataPath, OldPath: String;
begin
  Result := True;
  DataPath := GetDataDir('');
  OldPath := 'C:\אוצריא';
  
  // בדיקה אם יש התקנה ישנה בנתיב העברי
  if DirExists(OldPath) then
  begin
    if MsgBox('נמצאה התקנה ישנה ב-' + OldPath + #13#10 +
              'ספריית הספרים עוברת לנתיב חדש: ' + DataPath + #13#10#13#10 +
              'האם להעביר את הנתונים למיקום החדש?',
              mbConfirmation, MB_YESNO) = IDYES then
    begin
      // המשתמש יצטרך להעביר ידנית או שנוסיף קוד העברה
      MsgBox('לאחר ההתקנה, תוכל להעביר את הנתונים מ-' + OldPath + ' ל-' + DataPath, mbInformation, MB_OK);
    end;
  end;
  
  // בדיקה אם התיקיות קיימות והצגת אזהרה
  if DirExists(DataPath + '\books') then
  begin
    if MsgBox('שים לב: קיימים נתונים מספרייה ישנה בתיקייה ' + DataPath + '\books' + #13#10 +
              'הקודמים יימחקו ויוחלפו בנתוני ההתקנה החדשה.' + #13#10#13#10 +
              'האם להמשיך בהתקנה?',
              mbConfirmation, MB_YESNO) = IDNO then
    begin
      Result := False;
    end;
  end;
end;

function VCRedistNeedsInstall: Boolean;
var
  Version: String;
begin
  // Check if Visual C++ 2015-2022 Redistributable is installed
  // This checks for x64 version
  Result := not RegQueryStringValue(HKLM64, 'SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64', 
    'Version', Version);
  if not Result then
  begin
    // Also check x86 version
    Result := not RegQueryStringValue(HKLM64, 'SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x86', 
      'Version', Version);
  end;
end;

procedure ExtractBundledDatabase(const ArchiveName, DatabaseName: String);
var
  ArchivePath, DatabasePath, ZstdPath, Params: String;
  ResultCode: Integer;
begin
  ArchivePath := ExpandConstant('{app}\אוצריא\' + ArchiveName);
  if not FileExists(ArchivePath) then
  begin
    Log('Bundled database archive not found, skipping: ' + ArchivePath);
    exit;
  end;

  DatabasePath := ExpandConstant('{code:GetDataDir}\books\' + DatabaseName);
  ZstdPath := ExpandConstant('{app}\zstd.exe');

  ForceDirectories(ExtractFileDir(DatabasePath));

  Log('Extracting bundled database from ' + ArchivePath);
  Params := '-d -f -T0 --long=31 "' + ArchivePath + '" -o "' + DatabasePath + '"';

  if (not Exec(ZstdPath, Params, '', SW_HIDE, ewWaitUntilTerminated, ResultCode)) or (ResultCode <> 0) then
  begin
    MsgBox('חילוץ מסד הנתונים נכשל. קוד יציאה: ' + IntToStr(ResultCode), mbCriticalError, MB_OK);
    Abort;
  end;

  DeleteFile(ArchivePath);
end;

procedure ExtractBundledTarArchive(const ArchiveName, TargetDirName: String);
var
  ArchivePath, TarPath, ParentDir, TargetDir, ZstdPath, PowerShellPath, Params: String;
  ResultCode: Integer;
begin
  ArchivePath := ExpandConstant('{app}\אוצריא\' + ArchiveName);
  if not FileExists(ArchivePath) then
  begin
    Log('Bundled archive not found, skipping: ' + ArchivePath);
    exit;
  end;

  ParentDir := ExpandConstant('{code:GetDataDir}\books');
  TarPath := ParentDir + '\' + ChangeFileExt(ArchiveName, '');
  TargetDir := ExpandConstant('{code:GetDataDir}\books\' + TargetDirName);
  ZstdPath := ExpandConstant('{app}\zstd.exe');
  PowerShellPath := ExpandConstant('{sys}\WindowsPowerShell\v1.0\powershell.exe');

  if DirExists(TargetDir) then
  begin
    DelTree(TargetDir, True, True, True);
  end;
  ForceDirectories(TargetDir);

  Log('Extracting bundled tar archive from ' + ArchivePath);
  Params := '-d -f -T0 --long=31 "' + ArchivePath + '" -o "' + TarPath + '"';

  if (not Exec(ZstdPath, Params, '', SW_HIDE, ewWaitUntilTerminated, ResultCode)) or (ResultCode <> 0) then
  begin
    MsgBox('חילוץ ארכיון ה-PDF נכשל. קוד יציאה: ' + IntToStr(ResultCode), mbCriticalError, MB_OK);
    Abort;
  end;

  Params :=
    '-NoProfile -ExecutionPolicy Bypass -Command "tar -xf ''' + TarPath + ''' -C ''' +
    ParentDir + '''"';
  if (not Exec(PowerShellPath, Params, '', SW_HIDE, ewWaitUntilTerminated, ResultCode)) or
     (ResultCode <> 0) then
  begin
    MsgBox('פתיחת ארכיון ה-PDF נכשלה. קוד יציאה: ' + IntToStr(ResultCode), mbCriticalError, MB_OK);
    Abort;
  end;

  DeleteFile(TarPath);
  DeleteFile(ArchivePath);
  // Optional: Delete the bundled db directory since everything was extracted elsewhere
  // But maybe it's cleaner to handle this in a separate procedure if needed.
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ZstdPath: String;
  AppDataPath: string;
begin
  if CurStep = csInstall then
  begin
    if WizardIsTaskSelected('resetsettings') then
    begin
      // Delete previous installation directory (usually in LocalAppData)
      AppDataPath := ExpandConstant('{localappdata}\אוצריא');
      if DirExists(AppDataPath) then
        DelTree(AppDataPath, True, True, True);
        
      // Delete old settings and personal notes (in AppData/Roaming)
      AppDataPath := ExpandConstant('{userappdata}\com.example');
      if DirExists(AppDataPath) then
        DelTree(AppDataPath, True, True, True);
    end;
  end;

  if CurStep <> ssPostInstall then
    exit;

  ZstdPath := ExpandConstant('{app}\zstd.exe');

  if not FileExists(ZstdPath) then
  begin
    MsgBox('קובץ החילוץ zstd.exe לא נמצא. ההתקנה לא יכולה לחלץ את קבצי הספרייה המצורפים.', mbCriticalError, MB_OK);
    Abort;
  end;

  ExtractBundledDatabase('seforim.db.zst', 'seforim.db');
  ExtractBundledDatabase('otzar-HB_catalog.db.zst', 'otzar-HB_catalog.db');
  ExtractBundledTarArchive('talmud_bavli_latest.tar.zst', 'תלמוד בבלי');
  DeleteFile(ZstdPath);
  
  // Cleanup the temporary extraction directory
  DelTree(ExpandConstant('{app}\אוצריא'), True, True, True);
end;

[Run]
Filename: "{tmp}\VisualCppRedist_AIO_x86_x64.exe"; Parameters: "/ai /gm2"; StatusMsg: "מתקין Visual C++ Redistributable..."; Flags: waituntilterminated; Check: VCRedistNeedsInstall
Filename: "{app}\{#MyAppExeName}"; Description: "הפעל את {#MyAppName}"; Flags: nowait postinstall skipifsilent 

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "resetsettings"; Description: "איפוס הגדרות משתמש והסרת התקנות קודמות (מומלץ למעדכנים מגרסה < 0.9.80, שים לב: זה ימחק הערות אישיות!)"; Flags: unchecked

[Files]
; Copy DLL files without compression to prevent corruption
Source: "..\build\windows\x64\runner\Release\*.dll"; DestDir: "{app}"; Flags: ignoreversion nocompression
; Copy all other app files
Source: "..\build\windows\x64\runner\Release\*"; \
  Excludes: "*.dll"; \
    DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; Copy compressed library assets and extraction tool for post-install extraction
Source: "library_db\seforim.db.zst"; DestDir: "{app}\אוצריא"; Flags: ignoreversion
Source: "library_db\otzar-HB_catalog.db.zst"; DestDir: "{app}\אוצריא"; Flags: ignoreversion
Source: "library_db\talmud_bavli_latest.tar.zst"; DestDir: "{app}\אוצריא"; Flags: ignoreversion
Source: "zstd.exe"; DestDir: "{app}"; Flags: ignoreversion

Source: "VisualCppRedist_AIO_x86_x64.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall

[INI]
Filename: "{app}\system_install.marker"; Section: "Install"; Key: "Mode"; String: "Admin"; Check: IsAdminInstallMode
